### PR TITLE
Moved index.php -> public/index.php

### PR DESCRIPTION
**Pull request by sergeyklay**
Refs: #67, #69, #79

### CODE REVIEW

**Comment by sergeyklay** [comment]
Well, I managed it.
One big thing: I moved `core/assets` to the `public/assets`. Also I had a little play with `/fonts` response.

**Notice:** I updated Apache and Nginx configs: https://github.com/phanbook/phanbook/pull/78/commits/bd56c842180e9bd47141dc372e924e30061ca07b

@duythien Could you please take a look?

**Comment by sergeyklay** [comment]
webview

**Comment by duythien** [comment]
Absolutely, I want do it before now you do it, thanks :)

**Comment by sergeyklay** [comment]
Okay. I'll merge it. I'll examine possible problems with this. The `develop` branch still not ready to merge

**Pull request merged**
