### PR TITLE
Themes fixes

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@duythien 
Okay.
I managed to sort it finally.
As I said earlier the #78 is not final PR to fix `public/index.php` related issue.
And now I'm rolled back all assets to its original location.

I managed to solve the `public/index.php` related issue more fine tuning Apache (https://github.com/phanbook/phanbook/pull/87/commits/e4f20974bb51f5590bff9f7419c955f0eed378cb) and Nginx (https://github.com/phanbook/phanbook/pull/87/commits/e0067e300d9587971c0d2a3ea454dd11baef57b5). Now `development` branch is ready to merge to the `master` branch.

**Comment by sergeyklay** [comment]
webassets

**Comment by duythien** [comment]
Look good for me, now I was deploy to server dev http://dev.phanbook.com look good for now but It have a issue https://github.com/phanbook/phanbook/blob/master/content/themes/default/assets/css/app.css#L518 

In that case it will auto map http://dev.phanbook.com/images/chrome.png, but exactly this image into directory content/themes/default/assets/images

How to we can fix it

**Comment by sergeyklay** [comment]
@duythien I think we can rerite path like `../images/chrome.png` to `../<theme-name>/images/chrome.png` so we can write rules (Apache) or locations (Nginx) for it.

Can you do it?

**Comment by sergeyklay** [comment]
@duythien I think this is related https://github.com/phanbook/phanbook/blob/develop/core/common/tools/ZFunction.php#L43-L54

**Comment by duythien** [comment]
I see, but how we can get a `<theme-name>` into nginx rule?

**Comment by sergeyklay** [comment]
Each theme (for example `default`), **must** use paths like `../default/images/chrome.png`.

**Comment by sergeyklay** [comment]
So we can use regexp like `\w+/images/chrome.png`

**Comment by sergeyklay** [comment]
@duythien Well, as you can see I fixed it (right now for Apache): https://github.com/phanbook/phanbook/pull/94/commits/f45db35b8248f4af12d5f6b4705912e940541b42

fixed-assets-theme

Now all  themes shoud use absolute path, or (better) alias:

`/content/themes/<theme-name>/assets/images/chrome.png` => `/<theme-name>/images/chrome.png`

Could you please make the corresponding changes for `opsfiles/templates/nginx/vhost/phanbook.conf`?

**Comment by duythien** [comment]
Ok will do

**Pull request merged**
