### PR TITLE
update LICENSE.txt

### PR DESCRIPTION
**Pull request by kideny**

### CODE REVIEW

**Comment by kideny** [comment]
@duythien

**Review by sergeyklay — CHANGES_REQUESTED** [review]
Could you please check all project for `GNU` word?

**Review by kideny — COMMENTED** [review]
it's a big project ! haha

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Cc: @duythien

**Review by duythien — APPROVED** [review]

**Pull request merged**
